
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team02-m23-9am-1
owner: ucsb-cs156-m23
repo_name: team02-m23-9am-1
pull_requests: [{"author":{"id":"U_kgDOBnFUbw","is_bot":false,"login":"alecmorrison","name":""},"headRefName":"Alec-MenuItem","number":44,"title":"add entity and repository files for DiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-m23/team02-m23-9am-1/pull/44"},{"author":{"id":"U_kgDOBdDJ8w","is_bot":false,"login":"pabucsb","name":""},"headRefName":"Pablo-Menu-Controller","number":43,"title":"Pablo menu controller","url":"https://github.com/ucsb-cs156-m23/team02-m23-9am-1/pull/43"},{"author":{"id":"U_kgDOBczuwQ","is_bot":false,"login":"adhit-s","name":""},"headRefName":"Adhit-RecRequestTable","number":42,"title":"Adhit rec request table","url":"https://github.com/ucsb-cs156-m23/team02-m23-9am-1/pull/42"},{"author":{"id":"U_kgDOBdDJ8w","is_bot":false,"login":"pabucsb","name":""},"headRefName":"Pablo-Menu-Item","number":41,"title":"Pablo menu item","url":"https://github.com/ucsb-cs156-m23/team02-m23-9am-1/pull/41"}]
